### ISSUE TITLE
Documentation not accessible

### ISSUE THREAD

**Issue by kludikovsky** [shogun-toolbox/shogun#3178] opened 2016-04-23 16:21 UTC
The documentation on the Homepage leads to 404-Error

e.g. http://www.shogun-toolbox.org/doc/en/current/installation.html

**Comment by karlnapf** [comment] 2016-04-28 09:28
@vigsterkr any clues? I thought we had fixed this

**Comment by vigsterkr** [comment] 2016-04-28 12:50
@karlnapf ok so the problem is that at the time of `4.1.0` release there was a bug in doxygen config, hence it is 404. as you can see in case of latest it's fixed:
http://www.shogun-toolbox.org/doc/en/latest/installation.html

**Comment by vigsterkr** [comment] 2016-04-28 13:02
@karlnapf should we maybe port back that fix into current master?

**Comment by karlnapf** [comment] 2016-04-28 16:21
Ah yes, thanks for explaining. I think it might be a good idea to at least fix the docs online.
On the other hand, we can also just release ASAP and the 4.1 gets outdated anyways?
What do you think is better?

**Comment by vigsterkr** [comment] 2016-04-28 17:15
i'd say let's concentrate on the new release... :)

**Comment by karlnapf** [comment] 2016-04-29 11:20
Ok so this will be fixed once we release

**Closed** 2016-05-17 20:15 UTC
Labels: Documentation, website
