### ISSUE TITLE
RandomForest Regression exceptions using native or python interfaces

### ISSUE THREAD

**Issue by HunorSzabo** [shogun-toolbox/shogun#4051] opened 2017-12-25 20:31 UTC
Dear Contributors,

I am trying to run shogun on simple examples following the guidelines, but I am consistently getting exceptions. I tried it on Ubuntu 16.04(apt-get binaries and compiled it myself) and Windows 10 using the native c++ interface. Also tried the conda version from python both on Ubuntu and Windows with the same result.

See a simple example below:

```
#include <iostream>

#include <exception>

#include <fstream>
#include <sstream>

#include <shogun/features/DenseFeatures.h>
#include <shogun/labels/RegressionLabels.h>
#include <shogun/machine/RandomForest.h>
#include <shogun/ensemble/MajorityVote.h>
#include <shogun/base/init.h>

const int kNumberOfFeatures = 16;
const int kPositionSplit = 11;

void copyRow(shogun::SGMatrix<float64_t>& data, const std::vector<double>& row, int index) {
    for (int i = 0; i < row.size(); i++) {
        data.set_element(row[i], index, i);
    }
}

int main() {

    shogun::init_shogun();
    // Initializations
    std::vector<std::vector<double>> features;
    std::vector<double> labels;
    std::string::size_type sz;
    auto i = 0;

    // Read features
    std::ifstream featureFile("../X.txt");
    std::string line;
    while (std::getline(featureFile, line)) {
        std::istringstream tokenStream(line);
        std::string number;
        features.push_back(std::vector<double>(kNumberOfFeatures));
        auto j = 0;
        while(std::getline(tokenStream, number, ' ')) {
            double convertedNumber = std::stod(number, &sz);
            features[i][j++] = convertedNumber;
        }
        i++;
    }

    std::ifstream labelsStream("../Y.txt");
    while(std::getline(labelsStream, line)) {
        labels.push_back(std::stod(line, &sz));
    }

    // Splitting data
    int numberOfTest = features.size() / kPositionSplit;
    int numberOfTrain = features.size() - numberOfTest;
    shogun::SGMatrix<float64_t> trainingData(numberOfTrain, kNumberOfFeatures);
    shogun::SGMatrix<float64_t> trainingLabels(numberOfTrain, 1);
    shogun::SGMatrix<float64_t> testingData(numberOfTest, kNumberOfFeatures);
    shogun::SGMatrix<float64_t> testingLabels(numberOfTest, 1);

    for (auto i = 0; i < features.size(); i++) {
        int k,l;
        if (i % kPositionSplit != 0) {
            copyRow(trainingData, features[i], k++);
            trainingLabels = labels[i];
        } else {
            copyRow(testingData, features[i], l++);
            testingLabels = labels[i];
        }
    }

    // Use shogun
    auto features_train = new shogun::CDenseFeatures<float64_t>(trainingData);
    auto features_test = new shogun::CDenseFeatures<float64_t>(testingData);
    auto labels_train = new shogun::CRegressionLabels(trainingLabels);
    auto labels_test = new shogun::CRegressionLabels(testingLabels);
    auto featureTypes = shogun::SGVector<bool>(kNumberOfFeatures);
    featureTypes[12] = true;
    featureTypes[13] = true;
    featureTypes[14] = true;
    featureTypes[15] = true;

    try {
        shogun::CRandomForest randomForest(features_train, labels_train, 10, 5);
        auto voting = shogun::CMajorityVote();
        randomForest.set_combination_rule(&voting);
        randomForest.set_feature_types(featureTypes);
        randomForest.train();
    } catch (std::exception ex) {
        std::cout << ex.what() << std::endl;
    }
    return 0;
}
```

- OS: Windows 10, Ubuntu 16.04
- Version: 6.1.3, tried compiling from source, intalling it from ubuntu package manager and installing it by conda
- Interface: C++, Python

C++ Exception:
```
terminate called after throwing an instance of 'shogun::ShogunException'
Signal: SIGABRT (Aborted)

```
Python output
```
terminate called after throwing an instance of 'shogun::ShogunExceptionterminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
```

Let me know if I should attach the `Python` version. 
Any suggestions are very much appreciated, 
Thank you for your time, help and contribution to the opensource community,
Have a great holiday☃️
Best,
Hunor

**Comment by karlnapf** [comment] 2017-12-25 20:40
Hi!
This might well be a bug, shall we try to create a minimal python script to reproduce this?

**Comment by karlnapf** [comment] 2017-12-25 20:41
Or alternatively, can you share the data file and labels? Then I can try it locally

**Comment by HunorSzabo** [comment] 2017-12-25 20:52
Thanks for the lightning fast answer and support. I will add the data only do a quick sanitization first for privacy protection reason only.

**Comment by HunorSzabo** [comment] 2017-12-25 20:55
In the meantime here is also my python example, it is quite minimal already

   ```
X = # features
Y = # labels
 for k, (train, test) in enumerate(k_fold.split(X, Y)):
        x_train = X[train]
        y_train = Y[train]
        x_test = X[test]
        y_test = Y[test]
        features_train = RealFeatures(x_train)
        features_test = RealFeatures(x_test)
        labels_train = RegressionLabels(y_train)
        labels_test = RegressionLabels(y_test)
        featureTypes = np.array([True] * 11, np.bool)
        # featureTypes[11] = True
        # featureTypes[12] = True
        # featureTypes[13] = True
        # featureTypes[14] = True
        # featureTypes[15] = True

        randomForrest = RandomForest(features_train, labels_train, 5)
        randomForrest.set_feature_types(featureTypes)
        randomForrest.set_machine_problem_type(PT_REGRESSION)
        randomForrest.set_combination_rule(WeightedMajorityVote())

        try:
            randomForrest.train()
        except error:
            print(error)
```

**Comment by HunorSzabo** [comment] 2017-12-25 20:56
It crashes during `training` (by calling the `randomForrest.train()`. I tried to play by selecting only a small subset of features and data without any effect, crashes the same way whatever set of features or data I use for training.

**Comment by HunorSzabo** [comment] 2017-12-25 21:40
Here comes the sun🌞 , I mean the data.

[X.txt](https://drive.google.com/open?id=1zu7S8dOFVNLSlW6Gkki3j8q9e-yjg1cu) `16 features/line` separated by `one space`
[Y.txt](https://drive.google.com/open?id=1MPOSZ2hErfmdDNnboJt0J0O-aqNMSABu) labels

**Comment by karlnapf** [comment] 2017-12-26 00:43
Dummy data is fine (if it reproduces the error).

**Comment by HunorSzabo** [comment] 2017-12-26 11:36
Thanks for the reply @karlnapf. It certainly does reproduce the error in case it is not a configuration/usage mistake on my side, but it works flawlessly with Scikit.

**Comment by karlnapf** [comment] 2017-12-26 13:32
Cool, thanks. I will look into that a bit later today.

**Comment by karlnapf** [comment] 2017-12-27 00:28
Try to not set the feature types (I assume you want to do continuous features). There will be a warning, but it did not crash in my test (see above). This definitely is a bug. I will close this issue for now as we have #4054 in place. We can continue to discuss in here though

**Closed by karlnapf** 2017-12-27 00:28 UTC

**Comment by karlnapf** [comment] 2017-12-27 00:34
PS I made new code since yours was not standalone. But I think there is no qualitative difference

**Comment by HunorSzabo** [comment] 2017-12-27 15:08
Thanks for the quick feedback :+1: 

Actually the five features I use are categorical(0, 1) features :-s

**Comment by karlnapf** [comment] 2017-12-27 16:51
I am not sure what a weighted majority vote would mean for regression. Do you want to do classification?

As for the categorical features, yes that is definitely a bug. We need to investigate what is going on there.
I might have some time to do that in the near future, but I am away the next week unfortunately. I put up the description so that maybe somebody else could pick that up. Bear in mind it is holidays :)

**Comment by HunorSzabo** [comment] 2017-12-28 17:01
Currently, I am just evaluating the use of Shogun over other alternatives, so I am only testing around. 
Thank you for your effort and quick actions, I hope I could gather up some time and look into the issue, sorry if I seemed pushy about the fix, only wanted to make sure you have all the information.

Enjoy your holidays!
Bestbest,
Hunor

**Comment by karlnapf** [comment] 2018-01-11 17:52
Much appreciated thanks!
