### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by Thuva4** [shogun-toolbox/shogun#3583] opened 2016-12-19 16:40 UTC
I can not able to install shogun toolbox in Linux mint 18 . I got following error message.

'This PPA does not support xenial'
Cannot add PPA: ''This PPA does not support xenial''.

**Comment by karlnapf** [comment] 2016-12-21 17:51
Want to contribute one?
We might work on this early next year

**Comment by mohit9727** [comment] 2017-01-22 04:33
@karlnapf 
I want to take up this issue, any guidelines/roadmap that I should follow?

**Comment by karlnapf** [comment] 2017-01-23 16:04
Google is your friend here
@vigsterkr can also point to our current ppa configuation files

**Comment by vigsterkr** [comment] 2017-01-24 02:53
duplicate of #3576

**Closed by vigsterkr** 2017-01-24 02:53 UTC
