### ISSUE TITLE
Compilation error with g++ 6.1

### ISSUE THREAD

**Issue by jgomezlopez** [shogun-toolbox/shogun#3459] opened 2016-10-10 13:55 UTC
I'm trying to compile Shogun 4.1.0 in Debian Testing with cmake 3.6.2, g++ 6.1.1, octave 4.0.3, swig 3.0.7. I type the following commands in build directory I have just created.
$cmake .. -DoctaveModular=ON -DGENERATE_EXAMPLES=ON
$make
I get a compilation error when try to build class_list.cpp.o
In file included from /home/jose/software/shogun-4.1.0/src/shogun/kernel/normailizer/KernelNormalizer.h:16:0
from /home/jose/software/shogun-4.1.0/src/shogun/transfer/multitask/MultitaskKernelMaskPairNormalize.h:16
from /home/jose/software/shogun-4.1.0/src/shogun/base/class_list.cpp:18:
/home/jose/software/shogun-4.1.0/src/shogun/kernel/Kernel.h: In member function 'float64_t shogun::CKernel:kernel(int32_t, int32_t)':
/home/jose/software/shogun-4.1.0/src/shogun/kernel/Kernel.h: 212:21: error: invalid use of inclomplete type 'class shogun::CKernelNormalizer' return normalizer->normalize(compute(idx_a, idx_b), idx_a, idx_b);

**Comment by karlnapf** [comment] 2016-11-15 18:27
Is this still happening?

**Comment by jgomezlopez** [comment] 2016-11-29 16:16
Yes it is still happening. I tried to compile version 5.0 and the error is the same

In file included from /home/jose/software/shogun-shogun_5.0.0/src/shogun/kernel/normalizer/KernelNormalizer.h:16:0,
                 from /home/jose/software/shogun-shogun_5.0.0/src/shogun/transfer/multitask/MultitaskKernelMaskPairNormalizer.h:16,
                 from /home/jose/software/shogun-shogun_5.0.0/src/shogun/base/class_list.cpp:18:
/home/jose/software/shogun-shogun_5.0.0/src/shogun/kernel/Kernel.h: In member function ‘float64_t shogun::CKernel::kernel(int32_t, int32_t)’:
/home/jose/software/shogun-shogun_5.0.0/src/shogun/kernel/Kernel.h:213:21: error: invalid use of incomplete type ‘class shogun::CKernelNormalizer’
    return normalizer->normalize(compute(idx_a, idx_b), idx_a, idx_b);
                     ^~
In file included from /home/jose/software/shogun-shogun_5.0.0/src/shogun/kernel/normalizer/KernelNormalizer.h:16:0,
                 from /home/jose/software/shogun-shogun_5.0.0/src/shogun/transfer/multitask/MultitaskKernelMaskPairNormalizer.h:16,
                 from /home/jose/software/shogun-shogun_5.0.0/src/shogun/base/class_list.cpp:18:
/home/jose/software/shogun-shogun_5.0.0/src/shogun/kernel/Kernel.h:35:8: note: forward declaration of ‘class shogun::CKernelNormalizer’
  class CKernelNormalizer;
        ^~~~~~~~~~~~~~~~~
src/shogun/CMakeFiles/libshogun.dir/build.make:17093: fallo en las instrucciones para el objetivo 'src/shogun/CMakeFiles/libshogun.dir/base/class_list.cpp.o'
make[2]: *** [src/shogun/CMakeFiles/libshogun.dir/base/class_list.cpp.o] Error 1
CMakeFiles/Makefile2:286: fallo en las instrucciones para el objetivo 'src/shogun/CMakeFiles/libshogun.dir/all'

**Comment by besser82** [comment] 2017-01-19 09:00
Well, this happenes radomly…  Have seen this in various builds, when (re-)building Shogun for Fedora.  I'm currently trying to build 5.0.0 for Fedora and I cannot get a successful build, because at least one out of six different arches fails due to this problem and makes the package-build fail in whole.

Afaik, we need class_list.cpp for the SWIG'ed bindings…

**Comment by besser82** [comment] 2017-01-21 17:42
The madness continues…  :(

```
[ 53%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/base/class_list.cpp.o
cd /builddir/build/BUILD/shogun-5.0.0/py2/x86_64-redhat-linux-gnu/src/shogun && /usr/bin/c++    -I/builddir/build/BUILD/shogun-5.0.0/py2/src -I/builddir/build/BUILD/shogun-5.0.0/py2/src/shogun -I/builddir/build/BUILD/shogun-5.0.0/py2/x86_64-redhat-linux-gnu/src -I/builddir/build/BUILD/shogun-5.0.0/py2/x86_64-redhat-linux-gnu/src/shogun -isystem /usr/include/eigen3 -I/usr/lib64/../include -I/usr/include/json-c -I/usr/include/libxml2  -std=c++11 -Wall -Wno-unused-parameter -Wformat -Wformat-security -Wparentheses -Wshadow -Wno-unknown-pragmas -Wno-deprecated -O2 -g -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wno-misleading-indentation -fno-var-tracking-assignments -fopenmp -O2 -fPIC   -o CMakeFiles/libshogun.dir/base/class_list.cpp.o -c /builddir/build/BUILD/shogun-5.0.0/py2/src/shogun/base/class_list.cpp
make[2]: Leaving directory '/builddir/build/BUILD/shogun-5.0.0/py2/x86_64-redhat-linux-gnu'
In file included from /builddir/build/BUILD/shogun-5.0.0/py2/src/shogun/features/Alphabet.h:16:0,
                 from /builddir/build/BUILD/shogun-5.0.0/py2/src/shogun/lib/BitString.h:15,
                 from /builddir/build/BUILD/shogun-5.0.0/py2/src/shogun/base/class_list.cpp:15:
/builddir/build/BUILD/shogun-5.0.0/py2/src/shogun/lib/WrappedSGVector.h: In member function 'void shogun::CWrappedSGVector<T>::register_params()':
/builddir/build/BUILD/shogun-5.0.0/py2/src/shogun/base/SGObject.h:71:15: error: invalid use of incomplete type 'class shogun::Parameter'
   m_parameters->add(param, name, description);\
               ^
/builddir/build/BUILD/shogun-5.0.0/py2/src/shogun/base/SGObject.h:66:40: note: in expansion of macro 'SG_ADD4'
 #define VARARG_IMPL2(base, count, ...) base##count(__VA_ARGS__)
                                        ^~~~
/builddir/build/BUILD/shogun-5.0.0/py2/src/shogun/base/SGObject.h:67:39: note: in expansion of macro 'VARARG_IMPL2'
 #define VARARG_IMPL(base, count, ...) VARARG_IMPL2(base, count, __VA_ARGS__)
                                       ^~~~~~~~~~~~
/builddir/build/BUILD/shogun-5.0.0/py2/src/shogun/base/SGObject.h:68:27: note: in expansion of macro 'VARARG_IMPL'
 #define VARARG(base, ...) VARARG_IMPL(base, VA_NARGS(__VA_ARGS__), __VA_ARGS__)
                           ^~~~~~~~~~~
/builddir/build/BUILD/shogun-5.0.0/py2/src/shogun/base/SGObject.h:84:21: note: in expansion of macro 'VARARG'
 #define SG_ADD(...) VARARG(SG_ADD, __VA_ARGS__)
                     ^~~~~~
/builddir/build/BUILD/shogun-5.0.0/py2/src/shogun/lib/WrappedSGVector.h:84:3: note: in expansion of macro 'SG_ADD'
   SG_ADD(&m_value, "value", "Wrapped value", MS_NOT_AVAILABLE);
   ^~~~~~
/builddir/build/BUILD/shogun-5.0.0/py2/src/shogun/base/SGObject.h:34:7: note: forward declaration of 'class shogun::Parameter'
 class Parameter;
       ^~~~~~~~~
/builddir/build/BUILD/shogun-5.0.0/py2/src/shogun/base/SGObject.h:73:32: error: invalid use of incomplete type 'class shogun::Parameter'
    m_model_selection_parameters->add(param, name, description);\
                                ^
/builddir/build/BUILD/shogun-5.0.0/py2/src/shogun/base/SGObject.h:66:40: note: in expansion of macro 'SG_ADD4'
 #define VARARG_IMPL2(base, count, ...) base##count(__VA_ARGS__)
                                        ^~~~
/builddir/build/BUILD/shogun-5.0.0/py2/src/shogun/base/SGObject.h:67:39: note: in expansion of macro 'VARARG_IMPL2'
 #define VARARG_IMPL(base, count, ...) VARARG_IMPL2(base, count, __VA_ARGS__)
                                       ^~~~~~~~~~~~
/builddir/build/BUILD/shogun-5.0.0/py2/src/shogun/base/SGObject.h:68:27: note: in expansion of macro 'VARARG_IMPL'
 #define VARARG(base, ...) VARARG_IMPL(base, VA_NARGS(__VA_ARGS__), __VA_ARGS__)
                           ^~~~~~~~~~~
/builddir/build/BUILD/shogun-5.0.0/py2/src/shogun/base/SGObject.h:84:21: note: in expansion of macro 'VARARG'
 #define SG_ADD(...) VARARG(SG_ADD, __VA_ARGS__)
                     ^~~~~~
/builddir/build/BUILD/shogun-5.0.0/py2/src/shogun/lib/WrappedSGVector.h:84:3: note: in expansion of macro 'SG_ADD'
   SG_ADD(&m_value, "value", "Wrapped value", MS_NOT_AVAILABLE);
   ^~~~~~
/builddir/build/BUILD/shogun-5.0.0/py2/src/shogun/base/SGObject.h:34:7: note: forward declaration of 'class shogun::Parameter'
 class Parameter;
       ^~~~~~~~~
make[2]: *** [src/shogun/CMakeFiles/libshogun.dir/build.make:17117: src/shogun/CMakeFiles/libshogun.dir/base/class_list.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Entering directory '/builddir/build/BUILD/shogun-5.0.0/py2/x86_64-redhat-linux-gnu'
```

**Comment by besser82** [comment] 2017-01-21 18:41
This intercircular-header dependency-mess is so hard to fix…  -_-

**Comment by vigsterkr** [comment] 2017-02-12 13:33
started to pop up on our ppa builds: https://launchpadlibrarian.net/306118784/buildlog_ubuntu-xenial-amd64.shogun_5.1.0+1SNAPSHOT201702120915_BUILDING.txt.gz

**Comment by vigsterkr** [comment] 2017-02-12 13:40
i'm wondering whether an `os.walk` is always alphabetical - couldn't find out in the manual - or the output is actually not fixed and it's maybe even using inode to do the traversing?
i'm referring to this bit in `class_list.cpp.py`:
```
    for root, dirs, files in os.walk(basedir):
        for f in files:
            if f in class_headers:
                result.append(os.path.join(os.path.relpath(root, basedir), f))
```

i reckon an alphabetical sort on `result` wouldn't hurt... that way we are sure that the include order is *always* the same.

**Comment by vigsterkr** [comment] 2017-02-12 13:48
BINGO: http://stackoverflow.com/a/5667552/2798875

**Comment by vigsterkr** [comment] 2017-02-12 14:40
okey, the sorting of that `result` array solved the problem in the ppa build... any of you want to confirm if that's the case on your side as well?

**Comment by besser82** [comment] 2017-02-16 19:20
@vigsterkr I can confirm the patch works:  https://koji.fedoraproject.org/koji/buildinfo?buildID=859674

**Comment by vigsterkr** [comment] 2017-02-16 19:21
ok great thnx, closing!

**Closed by vigsterkr** 2017-02-16 19:21 UTC
