### ISSUE TITLE
include and import snippets in examples 

### ISSUE THREAD

**Issue by mhangaard** [shogun-toolbox/shogun#4817] opened 2020-02-10 15:43 UTC
In https://www.shogun-toolbox.org/examples/latest/index.html all tutorials begin with setting up some features and labels types, but all includes and imports are skipped. It would be convenient for the reader if include and import snippets were added at the beginning of each tutorial.

**Comment by karlnapf** [comment] 2020-02-10 21:41
Yes, this is "planned" for some time, but we never got around to doing it. Thought we had an issue for it already but couldnt find it....
Anyways, the ideal would be to have a button "show full lusting" that takes the reader to exactly that. It should not be too tricky to modify our sphinx plugin to generate that. Nice entrance task.

**Comment by thealphacod3r** [comment] 2020-02-13 15:14
@karlnapf would love to work on this!
can you guide me a little bit through this??

**Comment by krutikabapat** [comment] 2020-02-26 06:51
@karlnapf Can you please elaborate what exactly is expected by show full lusting so that I can work on it.

**Comment by vigsterkr** [comment] 2020-02-26 06:53
@krutikabapat the full source of the generated metaexample of a given language

**Comment by varsha753** [comment] 2020-03-29 15:01
[shogun_doc.pdf](https://github.com/shogun-toolbox/shogun/files/4399081/shogun_doc.pdf)

**Comment by varsha753** [comment] 2020-03-29 15:13
Here are some example for implementation of Shogun algorithms in python with imports  
[shogun_doc.pdf](https://github.com/shogun-toolbox/shogun/files/4399127/shogun_doc.pdf)

**Comment by karlnapf** [comment] 2020-03-29 15:39
Closing as duplicate of #4020

**Comment by karlnapf** [comment] 2020-03-29 15:40
@varsha753 please don't spam our issues in this way

**Closed as completed by karlnapf** 2020-03-29 15:39 UTC
Labels: good first issue, Tag: Documentation
