### ISSUE TITLE
the MKLClassification can't be trained 

### ISSUE THREAD

**Issue by joy1314** [shogun-toolbox/shogun#4446] opened 2018-12-21 01:07 UTC
I have installed the shogun by "conda install -c conda-forge shogun"
I have written codes like this 

def Bin_MKLClassficataion(f_feats_train,f_labels_train,f_feats_test,f_labels_test):
    features_train = RealFeatures(f_feats_train)
    labels_train = BinaryLabels(f_labels_train)
    features_test = RealFeatures(f_feats_test)
    labels_test = BinaryLabels(f_labels_test)

    poly_kernel = PolyKernel(10, 2)
    gauss_kernel_1 = GaussianKernel(2.0)
    gauss_kernel_2 = GaussianKernel(3.0)
    
    combined_kernel = CombinedKernel()
    combined_kernel.append_kernel(poly_kernel)
    combined_kernel.append_kernel(gauss_kernel_1)
    combined_kernel.append_kernel(gauss_kernel_2)
    combined_kernel.init(features_train, features_train)
    
    libsvm = LibSVM()
    svm = MKLClassification(libsvm)
    svm.set_interleaved_optimization_enabled(False)
    svm.set_kernel(combined_kernel)
    
    svm.set_labels(labels_train)
    svm.train()
    
    beta = combined_kernel.get_subkernel_weights()
    alpha = svm.get_alphas()
    
    combined_kernel.init(features_train, features_test)
    labels_predict = svm.apply_binary()
    error = MeanSquaredError()
    mse = error.evaluate(labels_predict, labels_test)
    return mse

But I met a error like this
Bin_MKLClassficataion
    svm.train()

SystemError: [ERROR] In file /home/conda/feedstock_root/build_artifacts/shogun-cpp_1540034967896/work/src/shogun/classifier/svm/LibSVM.cpp line 106: assertion kernel->get_num_vec_lhs()==problem.l failed in virtual bool shogun::CLibSVM::train_machine(shogun::CFeatures*) file /home/conda/feedstock_root/build_artifacts/shogun-cpp_1540034967896/work/src/shogun/classifier/svm/LibSVM.cpp line 106

what's wrong with my codes?
Thank you very much

**Comment by karlnapf** [comment] 2018-12-23 09:48
Nothing seems to be wrong on first sight. But you would need to post a fully stand-alone example that we can run to reproduce the error (use toy data)

**Comment by joy1314** [comment] 2018-12-26 00:11
@karlnapf I use the data from examples, but I got the same error. The complete code is like this.


import numpy as np
import pandas as pd

from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score
from sklearn.model_selection import KFold

from shogun import RealFeatures
from shogun import BinaryLabels
from shogun import MKLClassification
from shogun import CombinedKernel
from shogun import LibSVM
from shogun import StratifiedCrossValidationSplitting
from shogun import CrossValidation
from shogun import AccuracyMeasure
from shogun import CrossValidationResult
from shogun import ParameterObserverCV
from shogun import PolyKernel
from shogun import GaussianKernel
from shogun import MeanSquaredError


from getdata import get_data
from getdata import get_label_data
from getdata import remove_allzeros_lines

def Bin_MKLClassficataion(f_feats_train,f_labels_train,f_feats_test,f_labels_test):
    features_train = RealFeatures(f_feats_train)
    labels_train = BinaryLabels(f_labels_train)
    features_test = RealFeatures(f_feats_test)
    labels_test = BinaryLabels(f_labels_test)

    
    poly_kernel = PolyKernel(10, 2)
    gauss_kernel_1 = GaussianKernel(2.0)
    gauss_kernel_2 = GaussianKernel(3.0)
    
    
    combined_kernel = CombinedKernel()
    combined_kernel.append_kernel(poly_kernel)
    combined_kernel.append_kernel(gauss_kernel_1)
    combined_kernel.append_kernel(gauss_kernel_2)
    combined_kernel.init(features_train, features_train)
    
    libsvm = LibSVM()
    svm = MKLClassification(libsvm)
    svm.set_interleaved_optimization_enabled(False)
    svm.set_kernel(combined_kernel)
    
    svm.set_labels(labels_train)
    svm.train()
    
    
    combined_kernel.init(features_train, features_test)
    labels_predict = svm.apply_binary()
    error = MeanSquaredError()
    mse = error.evaluate(labels_predict, labels_test)
    return mse

train_data = pd.read_table('test_data/classifier_binary_2d_nonlinear_features_train.dat',header=None,sep=' ')
test_data=pd.read_table('test_data/classifier_binary_2d_nonlinear_features_test.dat',header=None,sep=' ')
train_label=pd.read_table('test_data/classifier_binary_2d_linear_labels_train.dat',header=None)
test_label=pd.read_table('test_data/classifier_binary_2d_linear_labels_test.dat',header=None)
train_data=train_data.values
test_data=test_data.values
train_labels=train_label.values
train_labels=train_labels.T
train_labels=train_labels[0]
test_labels=test_label.values
test_labels=test_labels.T
test_labels=test_labels[0]
result,k,w=Bin_MKLClassficataion(train_data,train_labels,test_data,test_labels)

**Comment by karlnapf** [comment] 2019-01-03 17:42
I am closing this due to a lack of a proper error report. Our CI indicates that all examples work. Feel free to re-open with a minimal, standalone example where you clearly highlight code, error messages, etc. Thanks

**Closed by karlnapf** 2019-01-03 17:42 UTC
