### ISSUE TITLE
missing openblas headers cause compile error

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#4000] opened 2017-12-03 13:16 UTC
```
[  3%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/classifier/svm/NewtonSVM.cpp.o
In file included from /opt/shogun/src/shogun/classifier/svm/NewtonSVM.cpp:20:0:
/opt/shogun/src/shogun/mathematics/lapack.h:41:19: fatal error: cblas.h: No such file or directory
 #include <cblas.h>
```

Installing `libopenblas-dev` solves that. Our cmake setup should catch this error before compilation. Alternatively there needs to be proper guarding in place.

**Comment by karlnapf** [comment] 2017-12-03 13:16
(and of course this is only true when *not* compiling against say anaconda's MKL blas/lapack

**Comment by vigsterkr** [comment] 2017-12-03 13:17
@karlnapf this is a duplicate of #3996 closing..

**Closed by vigsterkr** 2017-12-03 13:17 UTC
Labels: BUG, cmake, entrance
