### ISSUE TITLE
shogun error in compilation related to nlopt 

### ISSUE THREAD

**Issue by ahmedmazari** [shogun-toolbox/shogun#3632] opened 2017-02-17 02:08 UTC
after setting 
```
mkdir build
cd build
cmake -DENABLE_NLOPT=OFF -DPythonModular=ON ..
make

```
l even  removed nlopt  : 
`sudo apt-get remove python-nlopt`

if the problem comes from nlopt how to solve that 

[  1%] Generating version header
[  1%] Built target version
[  1%] Built target class_list
**[ 68%] Built target libshogun
[ 68%] Linking CXX shared library libshogun.so**
**/usr/bin/ld.gold: error: /usr/local/lib/liblzo2.a(lzo1x_1o.o): requires dynamic R_X86_64_PC32 reloc against 'memset' which may overflow at runtime; recompile with -fPIC**
/usr/bin/ld.gold: error: /usr/local/lib/liblzo2.a(lzo1x_9x.o): requires dynamic R_X86_64_PC32 reloc against 'memset' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/liblzo2.a(lzo_init.o): requires dynamic R_X86_64_PC32 reloc against '__stack_chk_fail' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(optimize.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_isinf' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(options.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(stop.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_isinf' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(timer.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(timer.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(timer.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(timer.o): requires dynamic R_X86_64_PC32 reloc against 'gettimeofday' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(timer.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(timer.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(direct_wrap.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(cdirect.o): requires dynamic R_X86_64_PC32 reloc against 'memcpy' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(praxis.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_stop_forced' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(plip.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(plis.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(pnet.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(pssubs.o): requires dynamic R_X86_64_PC32 reloc against 'sqrt' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(crs.o): requires dynamic R_X86_64_PC32 reloc against 'memcpy' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mlsl.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(ccsa_quadratic.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_count_constraints' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mma.o): requires dynamic R_X86_64_PC32 reloc against 'sqrt' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(cobyla.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_unscale' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(newuoa.o): requires dynamic R_X86_64_PC32 reloc against 'memset' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(nldrmd.o): requires dynamic R_X86_64_32 reloc which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(sbplx.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_stop_forced' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(auglag.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_stop_forced' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(bobyqa.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_unscale' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(isres.o): requires dynamic R_X86_64_PC32 reloc against 'ceil' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(slsqp.o): requires dynamic R_X86_64_PC32 reloc against 'sqrt' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(esch.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_urand' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(deprecated.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_local_search_alg_deriv' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(general.o): requires dynamic R_X86_64_32 reloc which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(general.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(general.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(general.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): requires unsupported dynamic reloc 11; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(qsort_r.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_qsort_r' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(redblack.o): requires unsupported dynamic reloc 11; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(rescale.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(sobolseq.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(DIRect.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(DIRserial.o): requires dynamic R_X86_64_PC32 reloc against 'direct_dirinfcn_' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(DIRsubrout.o): requires dynamic R_X86_64_PC32 reloc against 'direct_dirgetlevel_' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mssubs.o): requires dynamic R_X86_64_PC32 reloc against 'luksan_mxudot__' which may overflow at runtime; recompile with -fPIC
collect2: error: ld returned 1 exit status
src/shogun/CMakeFiles/shogun.dir/build.make:1472: recipe for target 'src/shogun/libshogun.so.17.2' failed
make[2]: *** [src/shogun/libshogun.so.17.2] Error 1
CMakeFiles/Makefile2:192: recipe for target 'src/shogun/CMakeFiles/shogun.dir/all' failed
make[1]: *** [src/shogun/CMakeFiles/shogun.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by vigsterkr** [comment] 2017-02-17 02:09
please stop pasting here huge debug content, use public services like pastebin.com

**Comment by ahmedmazari** [comment] 2017-02-17 02:11
sorry for that i though it s the right way to give further detail about the result of my compilation

**Comment by vigsterkr** [comment] 2017-02-17 02:11
this is obviously would not ever run currently:
```
cmake -DENABLE_NLOPT=OFF ..
cmake   cmake -DPythonModular=ON
make
```

before you continue this, please remove the created `build` directory and just run
```
mkdir build
cmake -DENABLE_NLOPT=OFF -DPythonModular=ON ..
make
```

**Comment by vigsterkr** [comment] 2017-02-17 02:12
and btw why do you want to build it from the source? if you just want on your ubuntu/debian system python modular interface use the ppa: https://launchpad.net/~shogun-toolbox/+archive/ubuntu/nightly

**Comment by ahmedmazari** [comment] 2017-02-17 02:27
thank you for your response. But when l execute `cmake -DENABLE_NLOPT=OFF -DPythonModular=ON .. `outside of build directory (l mean in shogun directory) l got this error 
`CMake Error: The source directory "/home/anelmad" does not appear to contain CMakeLists.txt.`
such that my path to shogun is `"/home/anelmad/shogun/ "`
and to build is `"/home/anelmad/shogun/build"`

2) you l should just use the ppa `sudo add-apt-repository ppa:shogun-toolbox/nightly` and l don't need sudo `add-apt-repository ppa:shogun-toolbox/stable` ?
3) how that is related to my error l got after 68 % compilation ?

**Comment by vigsterkr** [comment] 2017-02-17 02:29
ok so my apologies it should have been:
```
mkdir build
cd build
cmake -DENABLE_NLOPT=OFF -DPythonModular=ON ..
make
```

**Comment by vigsterkr** [comment] 2017-02-17 02:30
yes just add the nightly, and it's not related to your 68% but in case you just want to test shogun with python then that's more than enough for you....

**Comment by ahmedmazari** [comment] 2017-02-17 02:31
after executing `make` l got this error  now : 
`make: *** No targets specified and no makefile found.  Stop.`

**Comment by vigsterkr** [comment] 2017-02-17 02:33
```
cd /home/anelmad/shogun/build
cmake -DENABLE_NLOPT=OFF -DPythonModular=ON ..
make
```
if that's the output then you are clearly doing something very wrong sorry.... and i really cannot help you as this has nothing to do with shogun or cmake...

**Comment by ahmedmazari** [comment] 2017-02-17 02:37
actually it works. thus l come back to my origin error after 68 % compilation

**Comment by vigsterkr** [comment] 2017-02-17 02:39
can you copy the content of this file somewhere:
```/home/anelmad/shogun/build/src/shogun/lib/config.h```

**Comment by vigsterkr** [comment] 2017-02-17 02:40
btw you hand compiled and installed that nlopt..
either remove it or fix it... you have not compiled that nlopt adequately...
your nlopt is in `/usr/local/` prefix...

**Comment by ahmedmazari** [comment] 2017-02-17 02:47
l have in `/usr/local/include   nlopt.f  nlopt.h nlopt.hpp `
and in `/usr/local/lib  libnlopt.a libnlopt.la liblzo2.la`
can l remove them ?
2)
can you copy the content of this file somewhere:
`/home/anelmad/shogun/build/src/shogun/lib/config.h`
what do you mean by that ? for which purpose ? then l call that file ?

**Comment by vigsterkr** [comment] 2017-02-17 02:48
you can remove it or not as you wish.
clearly this is not a bug of shogun but your system - as state from the errors:
```
 /usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(mt19937ar.o): unsupported reloc 23 against local symbol
/usr/bin/ld.gold: error: /usr/local/lib/libnlopt.a(qsort_r.o): requires dynamic R_X86_64_PC32 reloc against 'nlopt_qsort_r' which may overflow at runtime; recompile with -fPIC
```

until you dont fix this error of your custom nlopt shogun will not be able to compile.

i'm closing this issues as it is clearly not shogun's error

**Closed by vigsterkr** 2017-02-17 02:48 UTC

**Comment by ahmedmazari** [comment] 2017-02-17 02:51
thank you alot for your valuable help
