### ISSUE TITLE
homepage 404 links

### ISSUE THREAD

**Issue by NightFantomJ2** [shogun-toolbox/shogun#3188] opened 2016-05-15 13:00 UTC
A lot of links on http://www.shogun-toolbox.org/ are giving 404 errors, e.g. http://www.shogun-toolbox.org/page/documentation/information -> click english installation gives a 404 here http://www.shogun-toolbox.org/doc/en/current/installation.html

**Comment by vigsterkr** [comment] 2016-05-18 03:02
duplicate of #3178

**Closed by vigsterkr** 2016-05-18 03:02 UTC
