### ISSUE TITLE
Add scale and add to linalg

### ISSUE THREAD

**Issue by karlnapf** [shogun-toolbox/shogun#2717] opened 2015-02-16 15:39 UTC
Search for "bvec.scale(-1.0);" in here
https://github.com/shogun-toolbox/shogun/pull/2676/files#r24749044

Talk to @lambday to get guidance.

**Comment by iglesias** [comment] 2015-02-19 15:32
I see both [scale](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/mathematics/linalg/internal/modules/Core.h#L85) and [add](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/mathematics/linalg/internal/modules/Core.h#L69) in linalg that should work for vectors. 

@lambday, is that right?

**Comment by lambday** [comment] 2015-02-20 05:49
@iglesias yes. The task is then to replace existing SGVector scale calls with linalg one.

**Comment by lambday** [comment] 2015-02-20 05:51
as well as remove scale from SGVector once everything is replaced. Links to SGVector cleanup issue #2582 as well :)

**Comment by nginn** [comment] 2015-10-24 11:49
Hi. I'm interested in contributing to Shogun and would like to start with this issue. @lambday is there anything else about this issue that I should know before starting?

**Comment by lambday** [comment] 2015-10-28 07:06
@nginn Hey! Thanks for your interest. This task is relatively simple - replace the existing member method calls for add and scale with linalg alternatives. Once it is done, we'd want the member methods for these two removed. Make sure you compile and run all the unit tests locally after your changes.

**Comment by nginn** [comment] 2015-10-30 18:53
Thanks, got it. Although, after doing some work on this issue, I have several questions:
1) how should I rely on unit-testing results if there are 4 failed tests currently? (build from d8eb73dd89f47e0da28f07163c4f635b96d0ec00) Should I consider it as a good result if after my changes there will be still the same number of failed tests?)
2) does this issue address the method SGVector::scale_vector, as long as SGVector::operator=+, too?

**Comment by lambday** [comment] 2015-10-31 04:28
Hi @nginn!

1) Yes! Your patch shouldn't introduce any new failing unit-tests than that are there  ;)
2) Good point. I think it does, because the overloaded `+` and `+=` operators use `add`. `scale_vector` should be fine for now since it doesn't depent on `scale`.

Suggestions: 
- handle `scale` and `add` in two different patches. Send one first, once that's merged, send the other patch.
- For both, you'd have to use the in-place version of the linalg methods. 
- One more thing, Say, you're replacing `scale` calls. Technically, you can just use `linalg::scale(a, alpha)` without specifying any backend which would then use a default backend to do the job and it will work, but it might cause problems in `viennacl` build since it is in-place operation. (There's a technical subtlety here which is not too important now. In case you're interested, check issue #2801). So, for now you should just use `NATIVE` backend explicitly for the task.

**Comment by nginn** [comment] 2015-10-31 20:45
@lambday I've send the scale() replacement in PR. Please have a look.

**Comment by nginn** [comment] 2015-11-19 21:25
@lambday Sorry for the long pause. I have another bunch of questions about the add method:
1) should I move both inplace operators `+=` to SGVector.cpp in order to avoid including linalg.h into SGVector.h? Of course I understand that this will make them non-inline. That's why I'm asking this question.
2) which backend for `linalg::add` should I use with SGSparseVector?

**Comment by lambday** [comment] 2015-11-20 11:41
Sorry @nginn I haven't looked at this PR in a while.

1. I didn't get why we would need to include `linalg.h` in `SGVector.h` even when the `operator+=` is there. It is in turn calling the `add` method, right? And that is defined in the cpp, not in header.  We can go crazy in the cpp and do all `linalg` nasty stuffs, but we should make sure that we don't miss an entire function definition if `linalg` isn't there (at least not for these trivial functions). So as long as the definition of `add` is available _even when_ `linalg.h` isn't there, we're good, right? I may miss something here, so please confirm if I am getting this right.
2. `linalg` doesn't deal with sparse vectors/matrices (yet). So maybe just leave that one for now :)

**Comment by nginn** [comment] 2015-11-20 16:41
@lambday 
1) seems like I'm the one with the wrong idea of what's going on. I assumed that as we need to remove `SGVector::scale` and this issue is about both `scale` and `add` the same applies to the `SGVector::add`. In case when I don't remove `SGVector::add` but just replace those calls outside the SGVector with the `linalg::add` all is ok and my first question is not actual.
2) I haven't found any issue about it. Can you please estimate the complexity of this task? I'm sure it will take me some time, but it's very interesting opportunity and I would definitely like to try. Until then I'll leave that one for now)

**Comment by nginn** [comment] 2015-11-20 16:45
@lambday so, just to be clear on this, operators in `SGVector` continue to use `SGVector:add` and this is not gonna be changed?

**Comment by lambday** [comment] 2015-11-21 06:28
@nginn ah sorry your assumption is right. I forgot that the task was to remove these methods altogether.  So regarding your query

1. yes, you'd need to move the definition of `operator+=` to the cpp and yes it would make them non-inline. I don't think that's gonna cost us too much. So just to get an idea, maybe try a benchmark with a vector and add it, say, a billion times and compare the performance of inlined `+=` and non-inlined `+=` (you can use hayai, see [this](https://github.com/shogun-toolbox/shogun/blob/develop/benchmarks/elementwise_benchmark.cpp) for an example). If in-lining does in fact make a difference, we can think of keeping it that way and not remove `add`. See we wanted to get rid of these methods in `SGMatrix` and `SGVector` to reduce the compilation time - (a) by having fewer methods to compile and (b) by reducing the size of the swig wrapper cpp. But these methods are invisible to swig anyway. So if we see the performance taking a hit, we can keep the methods and just replace the internals with `linalg` in the definition.
2. I don't know, honestly. See the issue is that we have a LIL implementation for sparse matrix, where as libraries like Eigen prefer CSC. So if you want to use Eigen backend for any operation involving `SGSparseMatrix`, it'll be spending quite a lot of its time on rearranging the data into their data structure, back and forth, which is clearly an overhead (we did that in some places though, see [this](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/mathematics/Statistics.cpp#L2200) for an example. Check [this benchmark](https://github.com/shogun-toolbox/shogun/blob/develop/benchmarks/sparse_test.cpp) too while we're at it). So we need to first come up with a list of operations for which it does make sense. We actually discussed a bit about this a few years back, talked about having an `EigenFactory` or so but couldn't get back to this issue for real after that. So, yes, it would be very interesting for sure. Thanks for bringing this up. Maybe we can create a new thread of issues regarding sparse linalg  :)

**Comment by nginn** [comment] 2015-12-03 17:12
1) I've created simple benchmark using hayai and it's results for inline and non-inline SGVector::operator+=(SGVector) didn't differ much.
This is result for inline operator+=:
```
[==========] Running 1 benchmark..
[ RUN      ] SGVector.addoperator_SGVector (10 runs, 100000000 iterations per run)
[     DONE ] SGVector.addoperator_SGVector (867014.567120 ms)
[   RUNS   ]        Average time: 86701456.712 us
                         Fastest: 86623911.212 us (-77545.500 us / -0.089 %)
                         Slowest: 86746861.212 us (+45404.500 us / +0.052 %)
                                  
             Average performance: 0.01153 runs/s
                Best performance: 0.01154 runs/s (+0.00001 runs/s / +0.08952 %)
               Worst performance: 0.01153 runs/s (-0.00001 runs/s / -0.05234 %)
[ITERATIONS]        Average time: 0.867 us
                         Fastest: 0.866 us (-0.001 us / -0.089 %)
                         Slowest: 0.867 us (+0.000 us / +0.052 %)
                                  
             Average performance: 1153383.15863 iterations/s
                Best performance: 1154415.66423 iterations/s (+1032.50560 iterations/s / +0.08952 %)
               Worst performance: 1152779.46202 iterations/s (-603.69661 iterations/s / -0.05234 %)
[==========] Ran 1 benchmark..
```
And this is for non-inline operator+=:
```
[==========] Running 1 benchmark..
[ RUN      ] SGVector.addoperator_SGVector (10 runs, 100000000 iterations per run)
[     DONE ] SGVector.addoperator_SGVector (869310.618160 ms)
[   RUNS   ]        Average time: 86931061.816 us
                         Fastest: 86625677.516 us (-305384.300 us / -0.351 %)
                         Slowest: 87580124.516 us (+649062.700 us / +0.747 %)
                                  
             Average performance: 0.01150 runs/s
                Best performance: 0.01154 runs/s (+0.00004 runs/s / +0.35253 %)
               Worst performance: 0.01142 runs/s (-0.00009 runs/s / -0.74111 %)
[ITERATIONS]        Average time: 0.869 us
                         Fastest: 0.866 us (-0.003 us / -0.351 %)
                         Slowest: 0.876 us (+0.006 us / +0.747 %)
                                  
             Average performance: 1150336.80610 iterations/s
                Best performance: 1154392.12561 iterations/s (+4055.31951 iterations/s / +0.35253 %)
               Worst performance: 1141811.57600 iterations/s (-8525.23010 iterations/s / -0.74111 %)
[==========] Ran 1 benchmark..
```
So, I moved SGVector::operator+=(SGVector) to .cpp file and replaced call to SGVector::add with linalg::add.
For now I leaved SGVector::operator+=(SGSparseVector) as it is.

2) Yes, new thread sounds good. I'm looking forward discussing these issues.

**Comment by karlnapf** [comment] 2015-12-13 17:48
@nginn Hi there.

Great stuff!
Are you interested in extending the linalg library with more operations like linear solves and more?
Seems like a good fit to you! Especially as you are doing these great benchmarks.
@lambday and @yorkerlin have plans to add the mentioned operations, so if you talk to them they can guide you

**Comment by nginn** [comment] 2015-12-14 19:53
@karlnapf Hi.
Yes, I am definitely interested. Thanks for the information!)

**Closed** 2019-01-26 18:00 UTC
Labels: development tasks, good first issue
