### ISSUE TITLE
Make fileson build target libshogun with Error 1 and Error 2

### ISSUE THREAD

**Issue by bhanratt** [shogun-toolbox/shogun#3436] opened 2016-08-23 18:55 UTC
This is driving me nuts. After spending hours installing all the dependencies I can't finish compiling. I have tried the stable release on the main website and also from cloning the development repository. I get this exact error every time:

[ 87%] Built target libshogun
Scanning dependencies of target shogun
Linking CXX shared library libshogun.so
/usr/bin/ld: /usr/local/lib/libnlopt.a(optimize.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libnlopt.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [src/shogun/libshogun.so.17.2] Error 1
make[1]: *** [src/shogun/CMakeFiles/shogun.dir/all] Error 2
make: *** [all] Error 2

**Comment by vigsterkr** [comment] 2016-08-23 18:57
@bhanratt could you please tell us your OS (and version).... and how did you install/get `libnlopt`?

**Comment by vigsterkr** [comment] 2016-08-23 19:02
basically the problem is rather with nlopt than shogun.... although i wonder why id doesn't try to link with the shared library of nlopt, i.e. `libnlopt.so` or `libnlopt.dylib`

**Comment by bhanratt** [comment] 2016-08-23 19:27
OS: Ubuntu 14.04 x86_64

**Comment by bhanratt** [comment] 2016-08-23 20:30
I have all the following installed from apt-get:
libnlopt-dev
libnlopt-guile0
libnlopt-guile0-dbgs
libnlopt0
libnlopt0-dbgsym
octave-nlopt
octave-nlopt-dbgsym
python-nlopt
python-nlopt-dbgsym

**Comment by vigsterkr** [comment] 2016-08-24 01:15
@bhanratt ok so first of all can you remove the manually built NLOPT or build it with `-fPIC` CFLAGS/CXXFLAGS as currently that's your problem that shogun is trying to use that manually built library that has not compiled with `-fPIC`.

btw this is a docker image (ubuntu 14.04) which has *all* the required/optional dependencies for shogun that we use for travis-ci. if in case you just wanna test shogun i reckon it's a much better way to get started:
https://hub.docker.com/r/shogun/shogun-dev/

**Comment by vigsterkr** [comment] 2016-08-24 01:16
@bhanratt if you dont mind i'll close this bug as it's really unrelated to shogun. but feel free to open it again if the problem remains after you've fixed the problem with nlopt.

**Closed by vigsterkr** 2016-08-24 01:16 UTC
