### ISSUE TITLE
C4.5 never ends

### ISSUE THREAD

**Issue by javiermaldonadoc** [shogun-toolbox/shogun#5035] opened 2020-05-14 20:57 UTC
Hello,

I'm using C4.5 algorithm to classify a dataset with 41 columns and 125K rows. It has 5 classes (multiclass). When try to train a C4.5 classifier it never ends. Keep running and give no response. This is the code:

    auto C45=std::make_shared<C45ClassifierTree>();
    C45->set_labels(sub_labels_train);
    C45->set_feature_types(subfeaType);

    C45->train(sub_features_train);
    auto C45fimportance = C45->get_feature_importances();
    auto C45labels_predict = C45->apply(sub_features_test)->as<MulticlassLabels>();

**Comment by karlnapf** [comment] 2020-05-15 09:32
Closing as duplicate of #5034

**Closed as completed by karlnapf** 2020-05-15 09:32 UTC
