### ISSUE TITLE
Segmentation fault when compiling Python bindings with SWIG 4

### ISSUE THREAD

**Issue by jamiesnape** [shogun-toolbox/shogun#4629] opened 2019-05-10 15:42 UTC
```
$ cmake .. -DBUILD_EXAMPLES=OFF -DBUNDLE_JSON=OFF -DBUNDLE_NLOPT=OFF -DENABLE_TESTING=OFF -DENABLE_CCACHE=OFF -DENABLE_COVERAGE=OFF -DBUILD_META_EXAMPLES=OFF -DINTERFACE_PYTHON=ON -DINTERFACE_JAVA=ON -DJBLAS=/usr/local/Cellar/shogun/6.1.3_3/libexec/jblas-1.2.3.jar -DLIB_INSTALL_DIR=/usr/local/Cellar/shogun/6.1.3_3/lib -DPYTHON_EXECUTABLE=/usr/local/opt/python@2/bin/python2 -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DPYTHON_LIBRARY=/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/Python -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/shogun/6.1.3_3 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang
-- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find CCache (missing: CCACHE CCACHE_VERSION) 
-- Found SWIG: /usr/local/bin/swig (found suitable version "4.0.0", minimum required is "3.0.5") 
-- Using system's malloc
-- Could NOT find GDB (missing: GDB_COMMAND GDB_VERSION) 
-- Found Doxygen: /usr/local/bin/doxygen (found suitable version "1.8.15", minimum required is "1.8.6") found components:  doxygen dot 
-- Found PythonInterp: /usr/local/opt/python@2/bin/python2 (found version "2.7.16") 
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- dir='/tmp/shogun-20190510-69364-1ron9wi/shogun-6.1.3/src'
-- dir='/tmp/shogun-20190510-69364-1ron9wi/shogun-6.1.3/build/src'
-- dir='/tmp/shogun-20190510-69364-1ron9wi/shogun-6.1.3/src/gpl'
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- Performing Test HAVE_CXA_DEMANGLE
-- Performing Test HAVE_CXA_DEMANGLE - Success
-- Looking for xmmintrin.h
-- Looking for xmmintrin.h - found
-- Looking for emmintrin.h
-- Looking for emmintrin.h - found
-- Looking for signgam
-- Looking for signgam - found
-- Looking for fdopen
-- Looking for fdopen - found
-- Looking for lgammal
-- Looking for lgammal - found
-- Found Eigen3: /usr/local/include/eigen3 (found suitable version "3.3.7", minimum required is "3.1.2") 
-- Found OPENCL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenCL.framework  
-- Could NOT find ViennaCL (missing: VIENNACL_INCLUDE_DIR VIENNACL_ENCODED_VERSION) (Required is at least version "1.5.0")
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
-- Could NOT find TFLogger (missing: TFLogger_DIR)
-- Looking for sgemm_
-- Looking for sgemm_ - not found
-- Looking for dgemm_
-- Looking for dgemm_ - found
-- Found BLAS: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Accelerate.framework  
-- Found Accelerate.framework using as BLAS/LAPACK backend.
-- Enabling Accelerate.framework as BLAS backend for Eigen.
-- Performing Test VECLIB_INCLUDE_WORKS
-- Performing Test VECLIB_INCLUDE_WORKS - Failed
-- Could not include <vecLib/cblas.h> hence not enabling LAPACK as an Eigen backend
-- Found GLPK: /usr/local/lib/libglpk.dylib  
-- Could NOT find CPLEX (missing: CPLEX_LIBRARY CPLEX_INCLUDE_DIR) 
-- Found Arpack : /usr/local/lib/libarpack.dylib
-- Could NOT find MOSEK (missing: MOSEK_DIR MOSEK_INCLUDE_DIR MOSEK_LIBRARY MOSEK_LIBRARIES) 
-- Found Protobuf: /usr/local/lib/libprotobuf.dylib (found version "3.7.1") 
-- Found JSON: /usr/local/include/json-c (found suitable version "0.13.01", minimum required is "0.11") 
-- Found LibXml2: /usr/lib/libxml2.dylib (found version "2.9.4") 
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /usr/local/lib/libhdf5.dylib;/usr/local/lib/libsz.dylib;/usr/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib (found version "1.10.5")  
-- Found CURL: /usr/lib/libcurl.dylib (found version "7.54.0")  
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11") 
-- Found BZip2: /usr/lib/libbz2.dylib (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Looking for lzma_auto_decoder in /usr/local/lib/liblzma.dylib
-- Looking for lzma_auto_decoder in /usr/local/lib/liblzma.dylib - found
-- Looking for lzma_easy_encoder in /usr/local/lib/liblzma.dylib
-- Looking for lzma_easy_encoder in /usr/local/lib/liblzma.dylib - found
-- Looking for lzma_lzma_preset in /usr/local/lib/liblzma.dylib
-- Looking for lzma_lzma_preset in /usr/local/lib/liblzma.dylib - found
-- Found LibLZMA: /usr/local/lib/liblzma.dylib (found version "5.2.4") 
-- Found SNAPPY: /usr/local/lib/libsnappy.dylib  
-- Lzo Library /usr/local/lib/liblzo2.dylib
-- Lzo Include Found in /usr/local/include
-- Found NLOPT: /usr/local/lib/libnlopt.dylib  
-- Could NOT find LPSOLVE (missing: LPSOLVE_LIBRARIES LPSOLVE_INCLUDE_DIR) 
-- Could NOT find ColPack (missing: COLPACK_LIBRARIES COLPACK_LIBRARY_DIR COLPACK_INCLUDE_DIR) 
-- Could NOT find ARPREC (missing: ARPREC_LIBRARIES ARPREC_INCLUDE_DIR) 
-- Looking for arc4random
-- Looking for arc4random - found
-- Linker: Default system linker
-- Checking to see if CXX compiler accepts flag -flto=thin
-- Checking to see if CXX compiler accepts flag -flto=thin - yes
-- The ctags found is not suitable for meta examples.
-- Could NOT find Ctags (missing: CTAGS_EXECUTABLE) 
-- Found PythonLibs: /usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/Python (found suitable exact version "2.7.16") 
-- Found NumPy: version "1.14.0" /usr/local/Cellar/shogun/6.1.3_3/libexec/vendor/lib/python2.7/site-packages/numpy/core/include
Using static linking for Python
-- Found Java: /Library/Java/JavaVirtualMachines/openjdk-12.0.1.jdk/Contents/Home/bin/java (found version "12.0.1") 
-- Found JNI: /Library/Java/JavaVirtualMachines/openjdk-12.0.1.jdk/Contents/Home/lib/libjawt.dylib  
-- Failed to locate sphinx-build executable (missing: SPHINX_EXECUTABLE) 
-- Found Pandoc: /usr/local/bin/pandoc  
-- ===================================================================================================================
-- Summary of Configuration Variables
-- The following OPTIONAL packages have been found:

 * Doxygen (required version >= 1.8.6)
 * CxaDemangle
 * Eigen3 (required version >= 3.1.2)
 * BLAS
 * GLPK
 * ARPACK
 * Protobuf
 * JSON (required version >= 0.11)
 * LibXml2
 * HDF5
 * CURL
 * ZLIB
 * BZip2
 * LibLZMA
 * SNAPPY
 * LZO
 * NLopt
 * Pandoc

-- The following REQUIRED packages have been found:

 * SWIG (required version >= 3.0.5)
 * PythonLibs (required version == 2.7.16)
 * PythonInterp
 * NumPy
 * Java
 * JNI

-- The following OPTIONAL packages have not been found:

 * CCache
 * GDB
 * OpenMP
 * ViennaCL (required version >= 1.5.0)
 * rxcpp
 * TFLogger (required version >= 0.1.0)
 * CPLEX
 * Mosek
 * LpSolve
 * ColPack
 * ARPREC
 * Ctags
 * Sphinx

-- ===================================================================================================================
-- Integrations
--   OpenCV Integration is OFF 	 enable with -DOpenCV=ON
-- ===================================================================================================================
-- Interfaces
--   Python is ON
--   Octave is OFF 		 enable with -DINTERFACE_OCTAVE=ON
--   Java is ON
--   Perl is OFF 		 enable with -DINTERFACE_PERL=ON
--   Ruby is OFF 		 enable with -DINTERFACE_RUBY=ON
--   C# is OFF 			 enable with -DINTERFACE_CSHARP=ON
--   R is OFF 			 enable with -DINTERFACE_R=ON
--   Lua is OFF 		 enable with -DINTERFACE_LUA=ON
--   Scala is OFF 		 enable with -DINTERFACE_SCALA=ON
-- ===================================================================================================================
-- To compile shogun type
--   make
-- 
-- To install shogun to /usr/local/Cellar/shogun/6.1.3_3 type
--   make install
-- 
-- or to install to a custom directory
--   make install DESTDIR=/my/special/path
--   (or rerun cmake with -DCMAKE_INSTALL_PREFIX=/my/special/path) to just change the prefix
-- ===================================================================================================================
-- Configuring done
-- Generating done
$ make install

[...]

cd /tmp/shogun-20190510-69364-1ron9wi/shogun-6.1.3/build/src/interfaces/python && /usr/local/bin/swig  -python -builtin -modern -modernargs -threads -w473 -w454 -w312 -w325 -fvirtual -outdir /tmp/shogun-20190510-69364-1ron9wi/shogun-6.1.3/build/src/interfaces/python -c++ -I/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/shogun/6.1.3_3/libexec/vendor/lib/python2.7/site-packages/numpy/core/include -I/tmp/shogun-20190510-69364-1ron9wi/shogun-6.1.3/src -I/tmp/shogun-20190510-69364-1ron9wi/shogun-6.1.3/build/src -I -I/tmp/shogun-20190510-69364-1ron9wi/shogun-6.1.3/src/gpl -I/usr/local/include/eigen3 -I/tmp/shogun-20190510-69364-1ron9wi/shogun-6.1.3/build/src/shogun/lib/external -I -I/usr/local/include -I/usr/local/include/json-c -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/libxml2 -I/usr/local/Cellar/hdf5/1.10.5_1/include -I/usr/local/opt/szip/include -o /tmp/shogun-20190510-69364-1ron9wi/shogun-6.1.3/build/src/interfaces/python/shogunPYTHON_wrap.cxx /tmp/shogun-20190510-69364-1ron9wi/shogun-6.1.3/build/src/interfaces/python/shogun.i
Deprecated command line option: -modern. This option is now always on.
Deprecated command line option: -modernargs. This option is now always on.
/tmp/shogun-20190510-69364-1ron9wi/shogun-6.1.3/src/shogun/lib/Hash.h:139: Warning 314: 'in' is a python keyword, renaming to '_in'
/tmp/shogun-20190510-69364-1ron9wi/shogun-6.1.3/src/shogun/lib/Signal.h:37: Warning 319: No access specifier given for base class 'CSGObject' (ignored).
/bin/sh: line 1: 74064 Segmentation fault: 11  /usr/local/bin/swig -python -builtin -modern -modernargs -threads -w473 -w454 -w312 -w325 -fvirtual -outdir /tmp/shogun-20190510-69364-1ron9wi/shogun-6.1.3/build/src/interfaces/python -c++ -I/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/shogun/6.1.3_3/libexec/vendor/lib/python2.7/site-packages/numpy/core/include -I/tmp/shogun-20190510-69364-1ron9wi/shogun-6.1.3/src -I/tmp/shogun-20190510-69364-1ron9wi/shogun-6.1.3/build/src -I -I/tmp/shogun-20190510-69364-1ron9wi/shogun-6.1.3/src/gpl -I/usr/local/include/eigen3 -I/tmp/shogun-20190510-69364-1ron9wi/shogun-6.1.3/build/src/shogun/lib/external -I -I/usr/local/include -I/usr/local/include/json-c -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/libxml2 -I/usr/local/Cellar/hdf5/1.10.5_1/include -I/usr/local/opt/szip/include -o /tmp/shogun-20190510-69364-1ron9wi/shogun-6.1.3/build/src/interfaces/python/shogunPYTHON_wrap.cxx /tmp/shogun-20190510-69364-1ron9wi/shogun-6.1.3/build/src/interfaces/python/shogun.i
make[2]: *** [src/interfaces/python/shogunPYTHON_wrap.cxx] Error 139
make[2]: *** Deleting file `src/interfaces/python/shogunPYTHON_wrap.cxx'
make[1]: *** [src/interfaces/python/CMakeFiles/_interface_python.dir/all] Error 2
```

**Comment by vigsterkr** [comment] 2019-05-11 07:15
@jamiesnape ooooh thnx for reporting! i dont think any of us tested swig 4.0 yet! will take a look at it and get back to you ASAP

**Comment by gf712** [comment] 2019-05-15 09:11
I can't reproduce the error locally (with latest develop). There are issues with SWIG 4.0.0 to compile the generated cxx file, but I don't get the segfault during generation of `shogunPYTHON_wrap.cxx`.

**Comment by vigsterkr** [comment] 2019-11-04 19:40
on azure we use swig 4.0.1 to generate the interfaces and all tests pass, so i'm closing this as fixed

**Closed by vigsterkr** 2019-11-04 19:40 UTC
